version: "3"

volumes:
  volume_name: 
    name: streampod_volume

services:
  db:
    image: postgres:15.2-alpine
    volumes:
      - ${PWD}/streampod_volume:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_DB: 'streampod'
      POSTGRES_USER: 'streampod'
      PGUSER:  'streampod'
      POSTGRES_PASSWORD: 'streampod'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "--host=db", "--dbname=$POSTGRES_DB", "--username=$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: "redis:alpine"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
  frontend:
    image: node:14
    volumes:
      - ${PWD}/frontend:/home/streampod.io/streampod/frontend/
    working_dir: /home/streampod.io/streampod/frontend/
    command: bash -c "npm install && npm run start"
    env_file:
      - ${PWD}/frontend/.env
    ports:
      - "8080:8080"
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    image: ocano/streampod-vms-dev:v1.1.2-qa
    environment:
      ADMIN_USER: 'admin'
      ADMIN_PASSWORD: 'admin'
      ADMIN_EMAIL: 'admin@localhost'
      POSTGRES_DB: 'streampod'
      POSTGRES_USER: 'streampod'
    ports:
      - "80:80"
    volumes:
      - ./:/home/streampod.io/streampod/
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
